# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('author_name', models.CharField(max_length=10, verbose_name='作者名称')),
                ('category', models.CharField(max_length=20, verbose_name='文章分类')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
            },
        ),
    ]
