# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='article_desc',
            field=models.CharField(default='正在添加...', max_length=300, verbose_name='文章正文'),
        ),
    ]
