# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_tags',
            field=models.ManyToManyField(to='articleApp.TagsModel', verbose_name='标签'),
        ),
    ]
