# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 01:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0002_articlemodel_article_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_desc',
            field=ckeditor.fields.RichTextField(default='正在添加...', max_length=300, verbose_name='文章正文'),
        ),
    ]
