# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 17:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0003_auto_20181130_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='正在添加...', max_length=300, verbose_name='文章正文'),
        ),
    ]
