# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0004_auto_20181130_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_name', models.CharField(max_length=100, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articleApp.CategoryModel', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articleApp.TagsModel', verbose_name='标签'),
        ),
    ]
