# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0005_auto_20181207_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='article_tags',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_tags',
            field=models.ManyToManyField(default='', to='articleApp.TagsModel', verbose_name='标签'),
        ),
    ]
