# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0002_auto_20181209_1929'),
        ('articleApp', '0006_auto_20181209_1855'),
    ]

    operations = [
    ]
