# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0008_auto_20181209_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='article_tags',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articleApp.TagsModel', verbose_name='标签'),
        ),
    ]
