# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 02:54
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('articleApp', '0009_auto_20181209_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='article_tags',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
