# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='博主昵称')),
                ('author_desc', models.TextField(max_length=100, verbose_name='博主信息')),
                ('author_wechat', models.CharField(max_length=10, verbose_name='博主微信')),
                ('author_qq', models.CharField(max_length=10, verbose_name='博主QQ')),
                ('author_weibo', models.CharField(max_length=10, verbose_name='博主微博')),
                ('author_github', models.CharField(max_length=10, verbose_name='博主github')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
        ),
    ]
