# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUserApp', '0003_blogauthormodel_author_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthormodel',
            name='author_logo',
            field=models.ImageField(blank=True, null=True, upload_to='i/author', verbose_name='博主头像'),
        ),
    ]
