# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfomodel',
            options={'verbose_name': '博客信息管理', 'verbose_name_plural': '博客信息管理'},
        ),
    ]
